"""identity_protocol_schema

Revision ID: 34106023f6bf
Revises: 510c8db33956
Create Date: 2026-05-18 13:35:09.748339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34106023f6bf'
down_revision: Union[str, Sequence[str], None] = '510c8db33956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_attestations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('riv_id', sa.String(), nullable=True),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('attestation_type', sa.String(), nullable=True),
    sa.Column('attestation_hash', sa.String(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('attestation_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identity_attestation_uid', 'identity_attestations', ['continuity_uid'], unique=False)
    op.create_table('identity_replay_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('rio_id', sa.String(), nullable=True),
    sa.Column('riv_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identity_replay_uid', 'identity_replay_events', ['continuity_uid'], unique=False)
    op.create_table('rig_objects',
    sa.Column('rig_id', sa.String(), nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('genesis_provider', sa.String(), nullable=True),
    sa.Column('genesis_country', sa.String(), nullable=True),
    sa.Column('genesis_hash', sa.String(), nullable=True),
    sa.Column('genesis_attestation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('rig_id'),
    sa.UniqueConstraint('continuity_uid')
    )
    op.create_index('idx_rig_continuity_uid', 'rig_objects', ['continuity_uid'], unique=False)
    op.create_table('rio_objects',
    sa.Column('rio_id', sa.String(), nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('rig_id', sa.String(), nullable=True),
    sa.Column('current_riv_id', sa.String(), nullable=True),
    sa.Column('trust_tier', sa.String(), nullable=True),
    sa.Column('corridor', sa.String(), nullable=True),
    sa.Column('identity_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('rio_id'),
    sa.UniqueConstraint('continuity_uid')
    )
    op.create_index('idx_rio_continuity_uid', 'rio_objects', ['continuity_uid'], unique=False)
    op.create_table('riv_objects',
    sa.Column('riv_id', sa.String(), nullable=False),
    sa.Column('rio_id', sa.String(), nullable=True),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('trust_tier', sa.String(), nullable=True),
    sa.Column('revision_reason', sa.String(), nullable=True),
    sa.Column('revision_metadata', sa.JSON(), nullable=True),
    sa.Column('attestation_reference', sa.String(), nullable=True),
    sa.Column('replay_generation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('riv_id')
    )
    op.create_index('idx_riv_continuity_uid', 'riv_objects', ['continuity_uid'], unique=False)
    op.create_index('idx_riv_revision', 'riv_objects', ['revision'], unique=False)
    op.create_table('zk_sd_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('riv_id', sa.String(), nullable=True),
    sa.Column('disclosure_type', sa.String(), nullable=True),
    sa.Column('zk_proof_hash', sa.String(), nullable=True),
    sa.Column('disclosure_scope', sa.String(), nullable=True),
    sa.Column('verifier_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_zksd_uid', 'zk_sd_records', ['continuity_uid'], unique=False)
    op.add_column('users', sa.Column('continuity_uid', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rig_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rio_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('active_riv_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('corridor', sa.String(), nullable=True))
    op.add_column('users', sa.Column('trust_tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('revision', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'national_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('idx_users_continuity_uid', 'users', ['continuity_uid'], unique=False)
    op.create_index('idx_users_rio', 'users', ['rio_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['rio_id'])
    op.create_unique_constraint(None, 'users', ['continuity_uid'])
    op.create_unique_constraint(None, 'users', ['rig_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_users_rio', table_name='users')
    op.drop_index('idx_users_continuity_uid', table_name='users')
    op.alter_column('users', 'national_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'revision')
    op.drop_column('users', 'trust_tier')
    op.drop_column('users', 'corridor')
    op.drop_column('users', 'active_riv_id')
    op.drop_column('users', 'rio_id')
    op.drop_column('users', 'rig_id')
    op.drop_column('users', 'continuity_uid')
    op.drop_index('idx_zksd_uid', table_name='zk_sd_records')
    op.drop_table('zk_sd_records')
    op.drop_index('idx_riv_revision', table_name='riv_objects')
    op.drop_index('idx_riv_continuity_uid', table_name='riv_objects')
    op.drop_table('riv_objects')
    op.drop_index('idx_rio_continuity_uid', table_name='rio_objects')
    op.drop_table('rio_objects')
    op.drop_index('idx_rig_continuity_uid', table_name='rig_objects')
    op.drop_table('rig_objects')
    op.drop_index('idx_identity_replay_uid', table_name='identity_replay_events')
    op.drop_table('identity_replay_events')
    op.drop_index('idx_identity_attestation_uid', table_name='identity_attestations')
    op.drop_table('identity_attestations')
    # ### end Alembic commands ###
