"""execution_event_indexes

Revision ID: 510c8db33956
Revises: 55ea2455cc11
Create Date: 2026-05-18 11:10:11.340169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '510c8db33956'
down_revision: Union[str, Sequence[str], None] = '55ea2455cc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_execution_events_continuity_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_tx_id'), table_name='execution_events')
    op.create_index('idx_execution_events_continuity', 'execution_events', ['continuity_id'], unique=False)
    op.create_index('idx_execution_events_created', 'execution_events', ['created_at'], unique=False)
    op.create_index('idx_execution_events_replay_generation', 'execution_events', ['replay_generation'], unique=False)
    op.create_index('idx_execution_events_tx', 'execution_events', ['tx_id'], unique=False)
    op.create_index('idx_execution_events_type', 'execution_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_execution_events_type', table_name='execution_events')
    op.drop_index('idx_execution_events_tx', table_name='execution_events')
    op.drop_index('idx_execution_events_replay_generation', table_name='execution_events')
    op.drop_index('idx_execution_events_created', table_name='execution_events')
    op.drop_index('idx_execution_events_continuity', table_name='execution_events')
    op.create_index(op.f('ix_execution_events_tx_id'), 'execution_events', ['tx_id'], unique=False)
    op.create_index(op.f('ix_execution_events_continuity_id'), 'execution_events', ['continuity_id'], unique=False)
    op.alter_column('execution_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
