"""add_execution_events_table

Revision ID: 55ea2455cc11
Revises: be47ce758d35
Create Date: 2026-05-18 11:04:04.205559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ea2455cc11'
down_revision: Union[str, Sequence[str], None] = 'be47ce758d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_id', sa.String(), nullable=False),
    sa.Column('continuity_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('lineage_parent', sa.String(), nullable=True),
    sa.Column('replay_generation', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_continuity_id'), 'execution_events', ['continuity_id'], unique=False)
    op.create_index(op.f('ix_execution_events_tx_id'), 'execution_events', ['tx_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_events_tx_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_continuity_id'), table_name='execution_events')
    op.drop_table('execution_events')
    # ### end Alembic commands ###
