"""railone_final_continuity_schema

Revision ID: 8f51defc879b
Revises: 
Create Date: 2026-05-18 22:44:08.988133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f51defc879b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('mirrored_available_state', sa.Float(), nullable=True),
    sa.Column('locked_mirrored_available_state', sa.Float(), nullable=True),
    sa.Column('execution_reservation', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_currency'), 'accounts', ['currency'], unique=False)
    op.create_index(op.f('ix_accounts_owner_id'), 'accounts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_accounts_provider'), 'accounts', ['provider'], unique=False)
    op.create_table('attestations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utt_id', sa.String(), nullable=True),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('attestation_type', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_checkpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utt_id', sa.String(), nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('checkpoint_state', sa.String(), nullable=False),
    sa.Column('replay_generation', sa.Integer(), nullable=True),
    sa.Column('execution_snapshot', sa.JSON(), nullable=True),
    sa.Column('integrity_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkpoint_continuity', 'execution_checkpoints', ['continuity_uid'], unique=False)
    op.create_index('idx_checkpoint_tx', 'execution_checkpoints', ['utt_id'], unique=False)
    op.create_index(op.f('ix_execution_checkpoints_continuity_id'), 'execution_checkpoints', ['continuity_uid'], unique=False)
    op.create_index(op.f('ix_execution_checkpoints_created_at'), 'execution_checkpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_checkpoints_tx_id'), 'execution_checkpoints', ['utt_id'], unique=False)
    op.create_table('execution_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utt_id', sa.String(), nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('replay_generation', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_continuity', 'execution_events', ['continuity_uid'], unique=False)
    op.create_index('idx_execution_tx_state', 'execution_events', ['utt_id', 'new_state'], unique=False)
    op.create_index(op.f('ix_execution_events_continuity_id'), 'execution_events', ['continuity_uid'], unique=False)
    op.create_index(op.f('ix_execution_events_created_at'), 'execution_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_events_tx_id'), 'execution_events', ['utt_id'], unique=False)
    op.create_table('identity_attestations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('riv_id', sa.String(), nullable=True),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('attestation_type', sa.String(), nullable=True),
    sa.Column('attestation_hash', sa.String(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('attestation_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identity_attestation_uid', 'identity_attestations', ['continuity_uid'], unique=False)
    op.create_table('identity_replay_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('rio_id', sa.String(), nullable=True),
    sa.Column('riv_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identity_replay_uid', 'identity_replay_events', ['continuity_uid'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utt_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rig_objects',
    sa.Column('rig_id', sa.String(), nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('genesis_provider', sa.String(), nullable=True),
    sa.Column('genesis_country', sa.String(), nullable=True),
    sa.Column('genesis_hash', sa.String(), nullable=True),
    sa.Column('genesis_attestation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('rig_id'),
    sa.UniqueConstraint('continuity_uid')
    )
    op.create_index('idx_rig_continuity_uid', 'rig_objects', ['continuity_uid'], unique=False)
    op.create_table('rio_objects',
    sa.Column('rio_id', sa.String(), nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('rig_id', sa.String(), nullable=True),
    sa.Column('current_riv_id', sa.String(), nullable=True),
    sa.Column('trust_tier', sa.String(), nullable=True),
    sa.Column('corridor', sa.String(), nullable=True),
    sa.Column('identity_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('rio_id'),
    sa.UniqueConstraint('continuity_uid')
    )
    op.create_index('idx_rio_continuity_uid', 'rio_objects', ['continuity_uid'], unique=False)
    op.create_table('riv_objects',
    sa.Column('riv_id', sa.String(), nullable=False),
    sa.Column('rio_id', sa.String(), nullable=True),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('trust_tier', sa.String(), nullable=True),
    sa.Column('revision_reason', sa.String(), nullable=True),
    sa.Column('revision_metadata', sa.JSON(), nullable=True),
    sa.Column('attestation_reference', sa.String(), nullable=True),
    sa.Column('replay_generation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('riv_id')
    )
    op.create_index('idx_riv_continuity_uid', 'riv_objects', ['continuity_uid'], unique=False)
    op.create_index('idx_riv_revision', 'riv_objects', ['revision'], unique=False)
    op.create_table('transactions',
    sa.Column('utt_id', sa.String(), nullable=False),
    sa.Column('sender_account', sa.String(), nullable=True),
    sa.Column('receiver_account', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('currency_from', sa.String(), nullable=True),
    sa.Column('currency_to', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('utt_id')
    )
    op.create_table('user_account_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('railone_id', sa.String(), nullable=True),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('external_account_ref', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('railone_id', sa.String(), nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('rig_id', sa.String(), nullable=True),
    sa.Column('rio_id', sa.String(), nullable=True),
    sa.Column('active_riv_id', sa.String(), nullable=True),
    sa.Column('corridor', sa.String(), nullable=True),
    sa.Column('trust_tier', sa.String(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('kyc_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('railone_id'),
    sa.UniqueConstraint('continuity_uid'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('rig_id'),
    sa.UniqueConstraint('rio_id')
    )
    op.create_index('idx_users_continuity_uid', 'users', ['continuity_uid'], unique=False)
    op.create_index('idx_users_rio', 'users', ['rio_id'], unique=False)
    op.create_table('zk_sd_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('continuity_uid', sa.String(), nullable=True),
    sa.Column('riv_id', sa.String(), nullable=True),
    sa.Column('disclosure_type', sa.String(), nullable=True),
    sa.Column('zk_proof_hash', sa.String(), nullable=True),
    sa.Column('disclosure_scope', sa.String(), nullable=True),
    sa.Column('verifier_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_zksd_uid', 'zk_sd_records', ['continuity_uid'], unique=False)
    op.create_table('institution_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('key_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institution_keys')
    op.drop_index('idx_zksd_uid', table_name='zk_sd_records')
    op.drop_table('zk_sd_records')
    op.drop_index('idx_users_rio', table_name='users')
    op.drop_index('idx_users_continuity_uid', table_name='users')
    op.drop_table('users')
    op.drop_table('user_account_links')
    op.drop_table('transactions')
    op.drop_index('idx_riv_revision', table_name='riv_objects')
    op.drop_index('idx_riv_continuity_uid', table_name='riv_objects')
    op.drop_table('riv_objects')
    op.drop_index('idx_rio_continuity_uid', table_name='rio_objects')
    op.drop_table('rio_objects')
    op.drop_index('idx_rig_continuity_uid', table_name='rig_objects')
    op.drop_table('rig_objects')
    op.drop_table('journal_entries')
    op.drop_table('institutions')
    op.drop_index('idx_identity_replay_uid', table_name='identity_replay_events')
    op.drop_table('identity_replay_events')
    op.drop_index('idx_identity_attestation_uid', table_name='identity_attestations')
    op.drop_table('identity_attestations')
    op.drop_index(op.f('ix_execution_events_tx_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_created_at'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_continuity_id'), table_name='execution_events')
    op.drop_index('idx_execution_tx_state', table_name='execution_events')
    op.drop_index('idx_execution_continuity', table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index(op.f('ix_execution_checkpoints_tx_id'), table_name='execution_checkpoints')
    op.drop_index(op.f('ix_execution_checkpoints_created_at'), table_name='execution_checkpoints')
    op.drop_index(op.f('ix_execution_checkpoints_continuity_id'), table_name='execution_checkpoints')
    op.drop_index('idx_checkpoint_tx', table_name='execution_checkpoints')
    op.drop_index('idx_checkpoint_continuity', table_name='execution_checkpoints')
    op.drop_table('execution_checkpoints')
    op.drop_table('attestations')
    op.drop_index(op.f('ix_accounts_provider'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_owner_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_currency'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
