"""execution_events

Revision ID: b62135bbb5c2
Revises: c62e3e75024c
Create Date: 2026-05-17 21:08:10.335361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62135bbb5c2'
down_revision: Union[str, Sequence[str], None] = 'c62e3e75024c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('mirrored_available_state', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('execution_reservation', sa.Float(), nullable=True))
    op.drop_column('accounts', 'locked_balance')
    op.drop_column('accounts', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('locked_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'execution_reservation')
    op.drop_column('accounts', 'mirrored_available_state')
    # ### end Alembic commands ###
