"""execution_state_defaults

Revision ID: bb7515f951db
Revises: b62135bbb5c2
Create Date: 2026-05-17 21:29:50.023639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7515f951db'
down_revision: Union[str, Sequence[str], None] = 'b62135bbb5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    # --------------------------------
    # RENAME COLUMN
    # --------------------------------
    op.alter_column(
        'accounts',
        'locked_mirrored_available_state',
        new_column_name='execution_reservation'
    )

    # --------------------------------
    # POPULATE NULL VALUES
    # --------------------------------
    op.execute("""
        UPDATE accounts
        SET execution_reservation = 0
        WHERE execution_reservation IS NULL
    """)

    # --------------------------------
    # ENFORCE NOT NULL
    # --------------------------------
    op.alter_column(
        'accounts',
        'execution_reservation',
        existing_type=sa.Float(),
        nullable=False,
        server_default='0'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('locked_mirrored_available_state', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('accounts', 'mirrored_available_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('accounts', 'execution_reservation')
    # ### end Alembic commands ###
