"""execution_event_store

Revision ID: be47ce758d35
Revises: bb7515f951db
Create Date: 2026-05-18 10:33:09.365699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be47ce758d35'
down_revision: Union[str, Sequence[str], None] = 'bb7515f951db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    UPDATE accounts
    SET mirrored_available_state = 0
    WHERE mirrored_available_state IS NULL
    """)

    op.execute("""
    UPDATE accounts
    SET execution_reservation = 0
    WHERE execution_reservation IS NULL
    """)

    op.alter_column('accounts', 'mirrored_available_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    UPDATE accounts
    SET mirrored_available_state = 0
    WHERE mirrored_available_state IS NULL
    """)

    op.execute("""
    UPDATE accounts
    SET execution_reservation = 0
    WHERE execution_reservation IS NULL
    """)


    op.alter_column('accounts', 'mirrored_available_state',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
