MPESA_TO_CANONICAL = {

    "0": "EXECUTION_SETTLED",

    "1": "EXECUTION_REJECTED",

    "1032": "EXECUTION_TIMEOUT",

    "1037": "EXECUTION_REQUIRES_RECOVERY",

    "2001": "EXECUTION_REJECTED",
}